Clienta/Models/Employee.cs
using Clienta.Services;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace Clienta.Models
{
    public class Employee : Person
    {
        [Display(Name = "Employee Number")]
        public int EmployeeNumber { get; set;  } = new Random().Next(100000, 999999);
        [Required]
        [Display(Name = "Start Date")]
        public DateTime StartDate { get; set; }
        public int? UserId { get; set; }
        public virtual User User { get; set; }
        [JsonIgnore]
        public virtual List<Client> Clients { get; set; }

        /// <summary>
        /// Get the Employee's Start Date formatted for readable display
        /// </summary>
        /// <returns>string - Formatted string representing short-form Date</returns>
        public string GetFormattedStartDate()
        {
            var startDateString = FormattingService.ConvertToShortUkFormat(this.StartDate);
            return $"{startDateString}";
        }
    }
}

Clienta/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Mvc;
using Clienta.Models;
using Clienta.Repositories.Interfaces;
using Clienta.Services.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Clienta.Controllers
{
    [Route("employees")]
    public class EmployeeController : Controller
    {
        private readonly IAuthenticationService _authentication;
        private readonly IEmployeeRepository _repository;
        private readonly IPaginationService _paginator;

        /// <summary>
        /// EmployeeController constructor
        /// </summary>
        /// <param name="authentication"></param>
        /// <param name="repository"></param>
        /// <param name="paginator"></param>
        public EmployeeController(IAuthenticationService authentication, IEmployeeRepository repository, IPaginationService paginator)
        {
            _authentication = authentication;
            _repository = repository;
            _paginator = paginator;
        }

        /// <summary>
        /// Retrieve the Employee browse page, with data
        /// </summary>
        /// <returns>RedirectToActionResult, or, View</returns>
        [HttpGet, ActionName("Browse")]
        [Route("")]
        public async Task<IActionResult> GetAll(int page = 1, string search = null)
        {
            if (!_authentication.IsAuthenticated(User))
            {
                return RedirectToAction("SignIn", "Authentication");
            }

            IEnumerable<Employee> employees = await _repository.BrowseAsync(search);

            int pageCount = _paginator.GetPageCount(employees.Count());
            int previousPage = _paginator.GetPreviousPageIndex(page);
            int nextPage = _paginator.GetNextPageIndex(page);

            ViewBag.PreviousPage = previousPage;
            ViewBag.NextPage = nextPage;
            ViewBag.HasPreviousPage = _paginator.IsPreviousPageAvailable(previousPage);
            ViewBag.HasNextPage = _paginator.IsNextPageAvailable(nextPage, pageCount);

            employees = employees
                .Skip(_paginator.PageSize * (page - 1))
                .Take(_paginator.PageSize)
                .ToList();

            return View("Browse", employees);
        }

        /// <summary>
        /// Retrieve a single Employee details page
        /// </summary>
        /// <param name="Id">Int: The Id of the record to action</param>
        /// <returns>RedirectToActionResult, or, View</returns>
        [HttpGet, ActionName("Read")]
        [Route("{Id:int}")]
        public async Task<IActionResult> GetOne([FromRoute] int Id)
        {
            if (!_authentication.IsAuthenticated(User))
            {
                return RedirectToAction("SignIn", "Authentication");
            }

            Employee employee = await _repository.ReadAsync(Id);
            return View("Detail", employee);
        }

        /// <summary>
        /// Retrieve the Employee creation view
        /// </summary>
        /// <returns>RedirectToActionResult, or, View</returns>
        [HttpGet]
        [Route("create")]
        public IActionResult Create()
        {
            if (!_authentication.IsAuthenticated(User))
            {
                return RedirectToAction("SignIn", "Authentication");
            }

            return View("Create");
        }

        /// <summary>
        /// Create a new Employee record
        /// </summary>
        /// <returns>RedirectToActionResult, or, View</returns>
        [HttpPost, ActionName("Create")]
        [Route("create")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Employee employee)
        {
            if (!_authentication.IsAuthenticated(User))
            {
                return RedirectToAction("SignIn", "Authentication");
            }

            if (!ModelState.IsValid)
            {
                return View("Create");
            }

            Employee newEmployee = await _repository.AddAsync(employee);
            return RedirectToAction("Read", "Employee", newEmployee);
        }

        /// <summary>
        /// Edit an existing Employee record
        /// </summary>
        /// <param name="Id">Int: The Id of the record to action</param>
        /// <param name="employee">Employee: The amended Client object</param>
        /// <returns>RedirectToActionResult, or, View</returns>
        [HttpPost, ActionName("Edit")]
        [Route("edit/{Id:int}")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromRoute] int Id, Employee employee)
        {
            if (!_authentication.IsAuthenticated(User))
            {
                return RedirectToAction("SignIn", "Authentication");
            }

            if (!ModelState.IsValid)
            {
                return RedirectToAction("Read", new { Id });
            }

            try
            {
                Employee editedEmployee = await _repository.EditAsync(Id, employee);
                if (editedEmployee != null)
                {
                    return RedirectToAction("Read", new { Id });
                }
                else
                {
                    return View("_NotFound");
                }
            }
            catch (Exception exc)
            {
                ViewBag.ErrorMessage = exc.Message;
                return View("_NotFound");
            }
        }

        /// <summary>
        /// Delete an Employee record
        /// </summary>
        /// <param name="Id">Int: The Id of the record to action</param>
        /// <returns>RedirectToActionResult, or, </returns>
        [HttpGet, ActionName("Delete")]
        [Route("delete/{Id:int}")]
        public async Task<IActionResult> Delete([FromRoute] int Id)
        {
            if (!_authentication.IsAuthenticated(User))
            {
                return RedirectToAction("SignIn", "Authentication");
            }

            try
            {
                Employee removedEmployee = await _repository.DeleteAsync(Id);
                if (removedEmployee != null)
                {
                    return RedirectToAction("Browse");
                }
                else
                {
                    return View("_NotFound");
                }
            }
            catch (Exception exc)
            {
                ViewBag.ErrorMessage = exc.Message;
                return View("_NotFound");
            }
        }
    }
}

Clienta/Views/ViewComponents/EmployeeFormViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Clienta.Models;
using Clienta.Services.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Clienta.Views.ViewComponents
{
    [ViewComponent]
    public class EmployeeFormViewComponent : ViewComponent
    {
        /// <summary>
        /// EmployeeFormViewComponent constructor
        /// </summary>
        public EmployeeFormViewComponent()
        {
        }

        /// <summary>
        /// Invoke the ViewComponent
        /// </summary>
        /// <param name="action">string - Controller action to invoke from ViewComponent Form</param>
        /// <param name="model">Employee - Plain Employee model for the ViewComponent</param>
        /// <returns>IViewComponentResult</returns>
        public IViewComponentResult Invoke(string action, Employee model)
        {            
            ViewData["Action"] = action;
            return View(model);
        }
    }
}

Clienta/Views/Employee/Browse.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model IEnumerable<Clienta.Models.Employee>
@{
    ViewData["Title"] = "Employees";
    ViewData["Entity"] = "Employee";
}

<div class="container col-10">
    <div class="row">
        <form asp-action="Browse" asp-controller="Employee" method="GET" class="col-12 pl-0 pr-4">
            <div class="input-group mt-3 mb-3">
                <input type="text" class="form-control" placeholder="@ViewData["Entity"] name" name="search" aria-label="@ViewData["Entity"] name">
                <div class="input-group-append">
                    <input type="submit" class="btn btn-primary" value="Search" />
                    <button href="@Url.Action("Browse", "Employee")" class="btn btn-primary">Clear</button>
                </div>
            </div>
        </form>
    </div>

    <div class="row table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Employee Id</th>
                    <th scope="col">Forname</th>
                    <th scope="col">Surname</th>
                    <th scope="col">Date of birth</th>
                    <th scope="col">Start Date</th>
                    <th scope="col">Employee Number</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                <tr>
                    <td scope="row">@item.Id</td>
                    <td scope="row">@item.Forename</td>
                    <td scope="row">@item.Surname</td>
                    <td scope="row">@item.GetFormattedDateOfBirth()</td>
                    <td scope="row">@item.GetFormattedStartDate()</td>
                    <td scope="row">@item.EmployeeNumber.ToString()</td>
                    <td scope="row">
                        <a class="btn btn-outline-primary" asp-action="Read" asp-controller="Employee" asp-route-id="@item.Id">Details</a>
                        <a class="btn btn-danger" asp-action="Delete" asp-controller="Employee" asp-route-id="@item.Id">Delete</a>
                    </td>
                </tr>
                }
            </tbody>
        </table>
        <div class="container">
            <div class="row">
                <div class="col-6">
                    <div class="pagination float-left">
                        @if (ViewBag.HasPreviousPage)
                        {
                            <a role="button" class="page-item btn btn-primary" href="@Url.Action("Browse", "Employee" , new { page = ViewBag.PreviousPage })">
                                &lt; Back
                            </a>
                        }
                        else
                        {
                            <a role="button" class="page-item btn btn-primary disabled" href="@Url.Action("Browse", "Employee" , new { page = ViewBag.PreviousPage })" aria-disabled="true">
                                &lt; Back
                            </a>
                        }
                    </div>
                </div>
                <div class="col-6">
                    <div class="pagination float-right">
                        @if (ViewBag.HasNextPage)
                        {
                            <a role="button" class="page-item btn btn-primary" href="@Url.Action("Browse", "Employee" , new { page = ViewBag.NextPage })">
                                Next &gt;
                            </a>
                        }
                        else
                        {
                            <a role="button" class="page-item btn btn-primary disabled" href="@Url.Action("Browse", "Employee" , new { page = ViewBag.NextPage })" aria-disabled="true">
                                Next &gt;
                            </a>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Clienta/Views/Employee/Create.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, Clienta
@model Clienta.Models.Employee
@{
    ViewData["Title"] = "Create Employee";
}

@await Component.InvokeAsync("EmployeeForm", new { Action = "Create", Model = @Model })

Clienta/Views/Employee/Detail.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, Clienta
@model Clienta.Models.Employee
@{
    ViewData["Title"] = "Employee details";
}

<div class="container">
    <div class="row mt-5">
        <div class="col-12 col-lg-4 mb-3">
            <img src="~/assets/avatar.png" class="mx-auto img-fluid img-circle d-block" alt="avatar">
        </div>

        <div class="col-12 col-lg-8 order-1">
            <ul class="nav nav-tabs" id="tab-navbar" role="tablist">
                <li class="nav-item" role="presentation">
                    <a class="nav-link active" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="true">Profile</a>
                </li>
                <li class="nav-item" role="presentation">
                    <a class="nav-link" id="associated-tab" data-toggle="tab" href="#associated" role="tab" aria-controls="associated" aria-selected="false">Associated</a>
                </li>
                <li class="nav-item" role="presentation">
                    <a class="nav-link" id="edit-tab" data-toggle="tab" href="#edit" role="tab" aria-controls="edit" aria-selected="false">Edit</a>
                </li>
            </ul>
            <div class="tab-content" id="tab-content-area">
                <div class="tab-pane fade show active" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                    <h5 class="mb-3 mt-5">Employee Profile</h5>
                    <div class="row">
                        <div class="col-md-6">
                            <h6>Name</h6>
                            <p>
                                @Model.GetFullname()
                            </p>
                        </div>

                        <div class="col-md-6">
                            <h6>Date of Birth</h6>
                            <p>
                                @Model.GetFormattedDateOfBirth()
                            </p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <h6>Employee Number</h6>
                            <p>
                                @Model.EmployeeNumber.ToString()
                            </p>
                        </div>

                        <div class="col-md-6">
                            <h6>Start Date</h6>
                            <p>
                                @Model.GetFormattedStartDate()
                            </p>
                        </div>
                    </div>
                </div>
                <div class="tab-pane fade" id="associated" role="tabpanel" aria-labelledby="associated-tab">
                    <h5 class="mb-3 mt-5">Associated Clients</h5>

                    @if (Model.Clients.Count > 0)
                    {
                        <table class="table table-sm table-hover table-striped">
                            <tbody>
                                @foreach (var client in Model.Clients)
                                {
                                    <tr scope="row">
                                        <td>@client.GetFullname() (@client.GetFormattedDateOfBirth())</td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    }
                    else
                    {
                        <p>No Clients have been associated with this Employee, yet. Please visit a Client's profile to assign them to this Employee.</p>
                    }
                </div>
                <div class="tab-pane fade" id="edit" role="tabpanel" aria-labelledby="edit-tab">
                    @await Component.InvokeAsync("EmployeeForm", new
                    {
                        Action = "Edit",
                        Model = @Model
                    })
                </div>
            </div>
        </div>
    </div>
</div>