Clienta/Models/Client.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace Clienta.Models
{
    public class Client : Person
    {
        [Display(Name = "Consultant")]
        public int? EmployeeId { get; set; }
        [JsonIgnore]
        public virtual Employee Employee { get; set; }
        public virtual List<Address> Addresses { get; set; }
    }
}

Clienta/Controllers/AddressController.cs
using Microsoft.AspNetCore.Mvc;
using Clienta.Models;
using Clienta.Repositories.Interfaces;
using Clienta.Services.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Clienta.Controllers
{
    [Route("addresses")]
    public class AddressController : Controller
    {
        private readonly IAuthenticationService _authentication;
        private readonly IAddressRepository _repository;

        /// <summary>
        /// AddressController constructor
        /// </summary>
        /// <param name="authentication"></param>
        /// <param name="repository"></param>
        public AddressController(IAuthenticationService authentication, IAddressRepository repository)
        {
            _authentication = authentication;
            _repository = repository;
        }

        /// <summary>
        /// Retrieve the Address creation view
        /// </summary>
        /// <returns>PartialView</returns>
        [HttpGet, ActionName("Create")]
        [Route("")]
        public IActionResult Create()
        {
            if (!_authentication.IsAuthenticated(User))
            {
                return RedirectToAction("SignIn", "Authentication");
            }

            return PartialView("_AddressModal", new Address { });
        }

        /// <summary>
        /// Create a new Address and associate it with a client
        /// </summary>
        /// <param name="clientId">The Id of the Client to associate the new Address with</param>
        /// <param name="address">The new Address Model</param>
        /// <returns>PartialView</returns>
        [HttpPost, ActionName("Create")]
        [Route("")]
        public async Task<IActionResult> Create([FromQuery] int clientId, Address address)
        {
            if (!_authentication.IsAuthenticated(User))
            {
                return RedirectToAction("SignIn", "Authentication");
            }

            if (!ModelState.IsValid)
            {
                return PartialView("_AddressModal", address);
            }
            
            address.ClientId = clientId;
            address.Postcode = address.Postcode.ToUpper();

            Address newAddress = await _repository.AddAsync(address);
            return PartialView("_AddressModal", newAddress);
        }
    }
}

Clienta/Controllers/ClientController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Clienta.Models;
using Clienta.Repositories.Interfaces;
using Clienta.Services.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Clienta.Controllers
{
    [Route("clients")]
    public class ClientController : Controller
    {
        private readonly IAuthenticationService _authentication;
        private readonly IClientRepository _repository;
        private readonly IPaginationService _paginator;

        /// <summary>
        /// ClientController constructor
        /// </summary>
        /// <param name="authentication"></param>
        /// <param name="repository"></param>
        /// <param name="paginator"></param>
        public ClientController(IAuthenticationService authentication, IClientRepository repository, IPaginationService paginator)
        {
            _authentication = authentication;
            _repository = repository;
            _paginator = paginator;
        }

        /// <summary>
        /// Retrieve the Client browse page, with data
        /// </summary>
        /// <returns>RedirectToActionResult, or, View</returns>
        [HttpGet, ActionName("Browse")]
        [Route("")]
        public async Task<IActionResult> GetAll(int page = 1, string search = null)
        {
            if (!_authentication.IsAuthenticated(User))
            {
                return RedirectToAction("SignIn", "Authentication");
            }

            IEnumerable<Client> clients = await _repository.BrowseAsync(search);

            int pageCount = _paginator.GetPageCount(clients.Count());
            int previousPage = _paginator.GetPreviousPageIndex(page);
            int nextPage = _paginator.GetNextPageIndex(page);

            ViewBag.PreviousPage = previousPage;
            ViewBag.NextPage = nextPage;
            ViewBag.HasPreviousPage = _paginator.IsPreviousPageAvailable(previousPage);
            ViewBag.HasNextPage = _paginator.IsNextPageAvailable(nextPage, pageCount);

            clients = clients
                .Skip(_paginator.PageSize * (page - 1))
                .Take(_paginator.PageSize)
                .ToList();

            return View("Browse", clients);
        }

        /// <summary>
        /// Retrieve a single Client details page
        /// </summary>
        /// <param name="Id">Int: The Id of the record to action</param>
        /// <returns>RedirectToActionResult, or, View</returns>
        [HttpGet, ActionName("Read")]
        [Route("{Id:int}")]
        public async Task<IActionResult> GetOne([FromRoute] int Id)
        {
            if (!_authentication.IsAuthenticated(User))
            {
                return RedirectToAction("SignIn", "Authentication");
            }

            Client client = await _repository.ReadAsync(Id);
            return View("Detail", client);
        }

        /// <summary>
        /// Retrieve the Client creation View
        /// </summary>
        /// <returns>RedirectToActionResult, or, View</returns>
        [HttpGet]
        [Route("create")]
        public IActionResult Create()
        {
            if (!_authentication.IsAuthenticated(User))
            {
                return RedirectToAction("SignIn", "Authentication");
            }

            return View("Create");
        }

        /// <summary>
        /// Create a new Client record
        /// </summary>
        /// <returns>RedirectToActionResult, or, View</returns>
        [HttpPost, ActionName("Create")]
        [Route("create")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Client client)
        {
            if (!_authentication.IsAuthenticated(User))
            {
                return RedirectToAction("SignIn", "Authentication");
            }

            if (!ModelState.IsValid)
            {
                return View("Create");
            }

            Client newClient = await _repository.AddAsync(client);
            return RedirectToAction("Read", "Client", newClient);
        }

        /// <summary>
        /// Edit an existing client record
        /// </summary>
        /// <param name="Id">Int: The Id of the record to action</param>
        /// <param name="client">Client: The amended Client object</param>
        /// <returns>RedirectToActionResult, or, View</returns>
        [HttpPost, ActionName("Edit")]
        [Route("edit/{Id:int}")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromRoute] int Id, Client client)
        {
            if (!_authentication.IsAuthenticated(User))
            {
                return RedirectToAction("SignIn", "Authentication");
            }

            if (!ModelState.IsValid)
            {
                return RedirectToAction("Read", new { Id });
            }

            try
            {
                Client editedClient = await _repository.EditAsync(Id, client);
                if (editedClient != null)
                {
                    return RedirectToAction("Read", new { Id });
                }
                else
                {
                    return View("_NotFound");
                }
            }
            catch (Exception exc)
            {
                ViewBag.ErrorMessage = exc.Message;
                return View("_NotFound");
            }
        }

        /// <summary>
        /// Delete a client record
        /// </summary>
        /// <param name="Id">Int: The Id of the record to action</param>
        /// <returns>RedirectToActionResult, or, View</returns>
        [HttpGet, ActionName("Delete")]
        [Route("delete/{Id:int}")]
        public async Task<IActionResult> Delete([FromRoute] int Id)
        {
            if (!_authentication.IsAuthenticated(User))
            {
                return RedirectToAction("SignIn", "Authentication");
            }

            try
            {
                Client removedClient = await _repository.DeleteAsync(Id);
                if (removedClient != null)
                {
                    return RedirectToAction("Browse");
                }
                else
                {
                    return View("_NotFound");
                }
            }
            catch (Exception exc)
            {
                ViewBag.ErrorMessage = exc.Message;
                return View("_NotFound");
            }
        }
    }
}

Clienta/Views/ViewComponents/ClientFormViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Clienta.Models;
using Clienta.Services.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Clienta.Views.ViewComponents
{
    [ViewComponent]
    public class ClientFormViewComponent : ViewComponent
    {
        private readonly IEmployeeService _employeeService;

        /// <summary>
        /// ClientFormViewComponent constructor
        /// </summary>
        /// <param name="employeeService">IEmployeeService</param>
        public ClientFormViewComponent(IEmployeeService employeeService)
        {
            _employeeService = employeeService;
        }

        /// <summary>
        /// Populates the Employee ViewBag property with a SelectList of Employees
        ///     and returns the ViewComponent
        /// </summary>
        /// <param name="action">string - Controller action to invoke from ViewComponent Form</param>
        /// <param name="model">Client - Plain Client model for the ViewComponent</param>
        /// <returns>IViewComponentResult</returns>
        public async Task<IViewComponentResult> InvokeAsync(string action, Client model)
        {            
            ViewData["Action"] = action;
            ViewBag.Employees = await _employeeService.GetEmployeeSelectListAsync();
            return View(model);
        }
    }
}

Clienta/Views/Client/Browse.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model IEnumerable<Clienta.Models.Client>
@{
    ViewData["Title"] = "Clients";
    ViewData["Entity"] = "Client";
}

<div class="container col-10">
    <div class="row">
        <form asp-action="Browse" asp-controller="Client" method="GET" class="col-12 pl-0 pr-4">
            <div class="input-group mt-3 mb-3">
                <input type="text" class="form-control" placeholder="@ViewData["Entity"] name" name="search" aria-label="@ViewData["Entity"] name">
                <div class="input-group-append">
                    <input type="submit" class="btn btn-primary" value="Search" />
                    <button href="@Url.Action("Browse", "Client")" class="btn btn-primary">Clear</button>
                </div>
            </div>
        </form>
    </div>

    <div class="row table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Client Id</th>
                    <th scope="col">Forname</th>
                    <th scope="col">Surname</th>
                    <th scope="col">Date of birth</th>
                    <th scope="col">Assigned Consultant</th>
                    <th scope="col">Addresses</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                <tr>
                    <td scope="row">@item.Id</td>
                    <td scope="row">@item.Forename</td>
                    <td scope="row">@item.Surname</td>
                    <td scope="row">@item.GetFormattedDateOfBirth()</td>
                    @if (item.Employee != null)
                    {
                        <td scope="row">@item.Employee.GetFullname()</td>
                    }
                    else
                    {
                        <td scope="row">N/A</td>
                    }
                    <td scope="row">
                        <ul>
                            @foreach (var address in item.Addresses)
                            {
                                <li>@address.ToString()</li>
                            }
                        </ul>
                    </td>
                    <td scope="row">
                        <a class="btn btn-outline-primary" asp-action="Read" asp-controller="Client" asp-route-id="@item.Id">Details</a>
                        <a class="btn btn-danger" asp-action="Delete" asp-controller="Client" asp-route-id="@item.Id">Delete</a>
                    </td>
                </tr>
                }
            </tbody>
        </table>
        <div class="container">
            <div class="row">
                <div class="col-6">
                    <div class="pagination float-left">
                        @if (ViewBag.HasPreviousPage)
                        {
                            <a role="button" class="page-item btn btn-primary" href="@Url.Action("Browse", "Client" , new { page = ViewBag.PreviousPage })">
                                &lt; Back
                            </a>
                        }
                        else
                        {
                            <a role="button" class="page-item btn btn-primary disabled" href="@Url.Action("Browse", "Client" , new { page = ViewBag.PreviousPage })" aria-disabled="true">
                                &lt; Back
                            </a>
                        }
                    </div>
                </div>
                <div class="col-6">
                    <div class="pagination float-right">
                        @if (ViewBag.HasNextPage)
                        {
                            <a role="button" class="page-item btn btn-primary" href="@Url.Action("Browse", "Client" , new { page = ViewBag.NextPage })">
                                Next &gt;
                            </a>
                        }
                        else
                        {
                            <a role="button" class="page-item btn btn-primary disabled" href="@Url.Action("Browse", "Client" , new { page = ViewBag.NextPage })" aria-disabled="true">
                                Next &gt;
                            </a>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Clienta/Views/Client/Create.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, Clienta
@model Clienta.Models.Client
@{
    ViewData["Title"] = "Create Client";
}

@await Component.InvokeAsync("ClientForm", new { Action = "Create", Model = @Model })

Clienta/Views/Client/Detail.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, Clienta
@model Clienta.Models.Client
@{
    ViewData["Title"] = "Client details";
}

<div class="container">
    <div class="row mt-5">
        <div class="col-12 col-lg-4 mb-3">
            <img src="~/assets/avatar.png" class="mx-auto img-fluid img-circle d-block" alt="avatar">
        </div>

        <div class="col-12 col-lg-8 order-1">
            <ul class="nav nav-tabs" id="tab-navbar" role="tablist">
                <li class="nav-item" role="presentation">
                    <a class="nav-link active" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="true">Profile</a>
                </li>
                <li class="nav-item" role="presentation">
                    <a class="nav-link" id="addresses-tab" data-toggle="tab" href="#addresses" role="tab" aria-controls="addresses" aria-selected="false">Addresses</a>
                </li>
                <li class="nav-item" role="presentation">
                    <a class="nav-link" id="associated-tab" data-toggle="tab" href="#associated" role="tab" aria-controls="associated" aria-selected="false">Associated</a>
                </li>
                <li class="nav-item" role="presentation">
                    <a class="nav-link" id="edit-tab" data-toggle="tab" href="#edit" role="tab" aria-controls="edit" aria-selected="false">Edit</a>
                </li>
            </ul>
            <div class="tab-content" id="tab-content-area">
                <div class="tab-pane fade show active" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                    <h5 class="mb-3 mt-5">Client Profile</h5>
                    <div class="row">
                        <div class="col-md-6">
                            <h6>Name</h6>
                            <p>
                                @Model.GetFullname()
                            </p>
                        </div>

                        <div class="col-md-6">
                            <h6>Date of Birth</h6>
                            <p>
                                @Model.GetFormattedDateOfBirth()
                            </p>
                        </div>
                    </div>
                </div>
                <div class="tab-pane fade" id="addresses" role="tabpanel" aria-labelledby="addresses-tab">
                    <h5 class="mb-3 mt-5">Client Addresses</h5>

                    @if (Model.Addresses.Count > 0)
                    {
                        <table class="table table-sm table-hover table-striped">
                            <tbody>
                                @foreach (var address in Model.Addresses)
                                {
                                    <tr scope="row">
                                        <td>@address.ToString()</td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    }
                    else
                    {
                        <p>This Client has no addresses yet. Please visit the Edit page to add a new Address.</p>
                    }
                    <div class="row float-right">
                        <!-- Button trigger Address creation modal -->
                        <div id="modal-target"></div>
                        <button type="button" class="btn btn-primary mr-3" data-toggle="ajax-modal" data-target="#create-address" data-url="@Url.Action("Create", "Address")">
                            Add
                        </button>
                    </div>
                </div>
                <div class="tab-pane fade" id="associated" role="tabpanel" aria-labelledby="associated-tab">
                    <h5 class="mb-3 mt-5">Associated Employees</h5>
                    <div class="row">
                        @if (Model.Employee != null)
                        {
                            <div class="col-md-6">
                                <h6>Name</h6>
                                <p>
                                    @Model.Employee.GetFullname()
                                    <span class="badge badge-primary"> Consultant</span>
                                </p>

                            </div>

                            <div class="col-md-6">
                                <h6>Employee Number</h6>
                                <p>
                                    @Model.Employee.EmployeeNumber
                                </p>
                            </div>
                        }
                        else
                        {
                            <p>This Client has no Employees associated, yet. Please visit the Edit page to assign one.</p>
                        }
                    </div>
                </div>
                <div class="tab-pane fade" id="edit" role="tabpanel" aria-labelledby="edit-tab">
                    @await Component.InvokeAsync("ClientForm", new
                    {
                        Action = "Edit",
                        Model = @Model
                    })
                </div>
            </div>
        </div>
    </div>
</div>